### ISSUE TITLE
Q: Do you know the hash used for passwords on HP Printers?

### ISSUE THREAD

**Issue by corsch** [breenmachine/HPwn#1]
Thank you for the great Backup decryption tool, but unfortunately the passwords are hashed / encrypted again.

Do you know the algorithm they use to create the password hashes?

**Comment by breenmachine** [comment]
I'm not sure, I haven't looked at this for a while and don't recall ever looking into the password hashing/encryption process. If you figure out how it works, it would be interesting to hear.
